version: '3'

services:

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_katari
      MYSQL_USER: katari
      MYSQL_PASSWORD: katari123456

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      FLASK_APP: backend/app/main.py
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://katari:katari123456@db:3306/db_katari

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  db-data: